### ISSUE TITLE
Using variables in file path

### ISSUE THREAD

**Issue by fasteR29** [Olyno/skent#11]
Why are these happening? 
`[15:59:46 WARN]: Exception in thread "insert ""[%now% / %the command sender%] %the chat message%"" at line {nowcmd::satırSayısı} of file/directory "plugins/fasteR/chatLog/%{nowcmd2}%.txt"" java.nio.file.InvalidPathException: Illegal char <<> at index 23: plugins/fasteR/chatLog/<none>.txt
[15:59:46 WARN]:        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
[15:59:46 WARN]:        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
[15:59:46 WARN]:        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
[15:59:46 WARN]:        at sun.nio.fs.WindowsPath.parse(Unknown Source)
[15:59:46 WARN]:        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
[15:59:46 WARN]:        at java.nio.file.Paths.get(Unknown Source)
[15:59:46 WARN]:        at com.olyno.skent.skript.expressions.ExprFileDirectory.get(ExprFileDirectory.java:56)
[15:59:46 WARN]:        at com.olyno.skent.skript.expressions.ExprFileDirectory.get(ExprFileDirectory.java:20)
[15:59:46 WARN]:        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:100)
[15:59:46 WARN]:        at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:58)
[15:59:46 WARN]:        at com.olyno.skent.skript.effects.EffInsertLine.executeAsync(EffInsertLine.java:67)
[15:59:46 WARN]:        at com.olyno.skent.util.AsyncEffect.run(AsyncEffect.java:44)
[15:59:46 WARN]:        at java.lang.Thread.run(Unknown Source)`

`[16:10:23 ERROR]: Can't understand this expression: date (faster-log.sk, line 11: insert "[%now% %sender%] %full command%" at line {chatLog::satırSayısı} of file path "plugins/fasteR/chatLog/%date%"')`

Also cant use %now% too so i am using `formatted as "dd/MM/yyyy HH.mm"`

the code:
`on command:
    if sender is a player:
        if difference between {nowcmd} and now is greater than 10 seconds:
            clear {nowcmd}
            clear {nowcmd2}
            wait a tick
            set {nowcmd} to now
            set {nowcmd2} to now formatted as "dd/MM/yyyy HH.mm"
            zip dir path "plugins/fasteR/chatLog" to dir path "plugins/fasteR/chatLogs.zip"
            wait a tick
            create file path "plugins/fasteR/chatLog/%{nowcmd2}%.txt"
            add 1 to {nowcmd::satırSayısı}
            insert "[%now% / %sender%] %full command%" at line {nowcmd::satırSayısı} of file path "plugins/fasteR/chatLog/%{nowcmd2}%.txt"
            send "[fasteR-chatLog.sk] Yeni dosya oluşturuldu ve eskisi sıkıştırıldı." to console
        else if difference between {nowcmd} and now is less than 10 seconds:
            set {_now::%sender's uuid%} to now formatted as "dd/MM/yyyy HH.mm"
            add 1 to {nowcmd::satırSayısı}
            insert "[%now% / %sender%] %full command%" at line {nowcmd::satırSayısı} of file path "plugins/fasteR/chatLog/%{nowcmd2}%.txt"`

**Comment by Olyno** [comment]
Please respect the issue template if you're reporting an issue.
