### ISSUE TITLE
Can't execute file because of X11

### ISSUE THREAD

**Issue by mcmatthevan** [Olyno/skent#14]
## Describe your problem

Hello,
I get a Warning when I try to execute a file, and the script is not executed.
It seems to be an issue with X11 DISPLAY variable. I tried to set it but it does not work.

## Versions

**Skript:** 2.5.3
**Server:** paper-457 (1.16.5)
**Skent:** 2.1.0

## Code

```vb
execute file path "plugins/Skript/prg.sh"
```

## Error
```
[17:36:42 WARN]: Exception in thread "execute file/directory "plugins/Skript/prg.sh"" java.awt.HeadlessException:
[17:36:42 WARN]: No X11 DISPLAY variable was set, but this program performed an operation which requires it.
[17:36:42 WARN]:        at java.desktop/java.awt.Desktop.getDesktop(Desktop.java:301)
[17:36:42 WARN]:        at com.olyno.skent.skript.effects.EffExecuteFile.executeAsync(EffExecuteFile.java:62)
[17:36:42 WARN]:        at com.olyno.skent.util.AsyncEffect.run(AsyncEffect.java:44)
[17:36:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Olyno** [comment]
The ``execute`` effect was pretty bad created. It will be fixed in the next release, thanks you for the report.
