### ISSUE TITLE
Problem while enabling

### ISSUE THREAD

**Issue by dominikd1977** [Olyno/skent#4]
Server version: 1.12.2 PaperSpigot
Skript version: Dev36

Error:

[08:26:14 ERROR]: Error occurred while enabling Skent v2.0.1 (Is it up to date?)
java.lang.NoClassDefFoundError: ch/njol/skript/conditions/base/PropertyCondition$PropertyType
        at com.olyno.skent.util.PriorityPropertyCondition.registerCondition(PriorityPropertyCondition.java:13) ~[?:?]
        at com.olyno.skent.skript.conditions.CondFileIsDir.<clinit>(CondFileIsDir.java:27) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_151]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_151]
        at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108) ~[?:?]
        at com.olyno.skent.Skent.onEnable(Skent.java:29) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: ch.njol.skript.conditions.base.PropertyCondition$PropertyType
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
        ... 17 more

**Comment by Govindass** [comment]
Skent only woroks with newer versions of Skript, since you're using 1.12.2, you can safely use the newest version of Skript, which is 2.5.1

**Comment by dominikd1977** [comment]
I just did that and now it works, thanks!
