### ISSUE TITLE
Sign save into file not work.

### ISSUE THREAD

**Issue by Misio12320** [Olyno/skent#7]
## Describe your problem

The issue is weird, code is wrote correct as I see and should work.
It save but write only this:
```[01.12.2020 19:57:41]  <x: 5.5; y: 70.5; z: 77.5; świat: world:
``` and not full text and lines of sign. I want to only use Skent for better performance without installing more addons.
## Versions

**Skript:** <Skript Version: 2.5.1> (``/ver skript``)
**Server:** <Paper version git-Paper-282> (``/ver``)
**Skent:** <Skent v2.0.1> (``/ver skent``)

## Code

```vb
on sign change:
	if file path "tabliczki/tabliczki.txt" is missing:
		create file path "tabliczki/tabliczki.txt"
	set {_now} to now formatted as "[dd.MM.yyyy HH:mm:ss]"
	set {_loc} to "<x: %x-loc of event-block%; y: %y-loc of event-block%; z: %z-loc of event-block%; świat: %world%:"
	add "" and "%{_now}%  %{_loc}%" to {_list::*}
	append "%{_now}%  %{_loc}%" to file path "tabliczki/tabliczki.txt"
	loop 4 times:
		add "- %line loop-number%" to {_list::*}
	append {_list::*} to file path "tabliczki/tabliczki.txt"
	add content of file path "tabliczki/tabliczki.txt" to {_list::*}
```

**Comment by Olyno** [comment]
Sorry but I didn't understand what was wrong with your code. Can you try to explain it again please?

**Comment by Misio12320** [comment]
Sorry I see something I broke with the issue. The issue is the signs should be saved into file.txt after closing the GUI of sign. Should be wrie in this way:
%now% %loc%
Line 1
Line 2
Line 3
Line 4
Stop
But it write in this way:

**Comment by Olyno** [comment]
Can you give the whole error please?

**Comment by Misio12320** [comment]
This is only this, when reload says everything work. 
Reloading signs.sk...
[14:21:21 INFO]: [Skript] Successfully reloaded signs.sk.

**Comment by Olyno** [comment]
> And heres the message from console

Can you post the whole error please?

**Comment by Misio12320** [comment]
![bandicam 2020-12-02 15-41-13-555](https://user-images.githubusercontent.com/42146429/100887105-e07d5580-34b4-11eb-81d2-b85d3a35aa01.jpg)
Exception in thread "append {_list::*} to file/directory "tabliczki/tabliczki.txt"" java.util.ConcurrentModificationException [20:29:51 WARN]: at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1211) [20:29:51 WARN]: at java.util.TreeMap$EntryIterator.next(TreeMap.java:1247) [20:29:51 WARN]: at java.util.TreeMap$EntryIterator.next(TreeMap.java:1242) [20:29:51 WARN]: at ch.njol.skript.lang.Variable.get(Variable.java:294) [20:29:51 WARN]: at ch.njol.skript.lang.Variable.getConvertedArray(Variable.java:436) [20:29:51 WARN]: at ch.njol.skript.lang.Variable.getAll(Variable.java:659) [20:29:51 WARN]: at ch.njol.skript.lang.Variable.getArray(Variable.java:652) [20:29:51 WARN]: at com.olyno.skent.skript.effects.EffAppendFile.executeAsync(EffAppendFile.java:69) [20:29:51 WARN]: at com.olyno.skent.util.AsyncEffect.run(AsyncEffect.java:44) [20:29:51 WARN]: at java.lang.Thread.run(Thread.java:748) only this I have

**Comment by Misio12320** [comment]
The issue got fixed. Nevermind this thread
